# Generated by Django 5.1.4 on 2024-12-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
