# Generated by Django 5.2 on 2025-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_proof',
            field=models.FileField(upload_to='Assets/Shop/Proof/'),
        ),
    ]
